name: CI Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black to test code linting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true
      - name: Run isort to organize imports
        uses: isort/isort-action@master
  static-type-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -U git+https://github.com/python/mypy.git@9a10967fdaa2ac077383b9eccded42829479ef31
      # Note: if mypy issue #5485 gets resolved, we can install from head again.
    - name: Mypy
      run: |
        mypy . --config-file mypy.ini